server:
  # 修改springboot项目端口号
  port: 8888
  # 修改项目的部署的上下文路径
  servlet:
    context-path: /
# 配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db19?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: ok

# 配置mybatis
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.feng480.entity
  #打印sql语句的日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
